### ISSUE TITLE
In RTL OTP View strange Behaviour

### ISSUE THREAD

**Issue by milindvyas008** [mukeshsolanki/android-otpview-pinview#10]
I Change it to RTL and OTP view focus also changed now its focusing 2nd box first and then after it is focusing on the first view and then third. Please help me how can i overcome this issue for RTL?
Thanks for sharing this. need your support.

**Comment by mukeshsolanki** [comment]
@milindvyas008 can you try the latest version `1.0.5`?

**Comment by mukeshsolanki** [comment]
@milindvyas008 an update on this?
