### ISSUE TITLE
How to switch between hide and view value

### ISSUE THREAD

**Issue by adnanganie** [mukeshsolanki/android-otpview-pinview#103]
### Subject of the issue
Like toggle on Password

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by mukeshsolanki** [comment]
Why would an otp view require a toggle?

**Comment by adnanganie** [comment]
Sometimes user wants to see what i had typed (value)

**Comment by mukeshsolanki** [comment]
This is a specific issue catered to your needs and it should not be a part of the lib. You can achieve this by having the button remove the mask and replace it with the entered value

**Comment by adnanganie** [comment]
I did using checkbox

**Comment by nikharsachdeva** [comment]
> I did using checkbox

Can you help me with the snippet?
