### ISSUE TITLE
Soft Keyboard not showing 

### ISSUE THREAD

**Issue by phineas-in** [mukeshsolanki/android-otpview-pinview#106]
OTP view is not having the focus, when we did all programmatically and imply force soft keyboard then keyboard is working but 
the text entered is not getting entered in textbox

**Comment by yemyatthu1990** [comment]
@Phineas019 you need to add <item name="otpViewStyle">@style/OtpWidget.OtpView</item> to the app theme.

**Comment by phineas-in** [comment]
Hey @yemyatthu1990  I did the thing is working in Emulator not on a physical device

**Comment by vishalvishvakarma** [comment]
add this line in xml 
this work for me 
android:focusable="true"

**Comment by PembaTamang** [comment]
not working on my samsung a50s running one ui 2.0 based on android 10

**Comment by udhayab2q** [comment]
keyboard Not Working

**Comment by udhayab2q** [comment]
> @Phineas019 you need to add @style/OtpWidget.OtpView to the app theme.

Yes is it working thank you @Phineas019

**Comment by pratikbutani** [comment]
Add following line to your `style.xml`

		<item name="otpViewStyle">@style/OtpWidget.OtpView</item>
