### ISSUE TITLE
OTP View android:textAllCaps="true" is ignored

### ISSUE THREAD

**Issue by ablenesi** [mukeshsolanki/android-otpview-pinview#107]
### Subject of the issue
Setting `android:textAllCaps="true"` to the view does not force capps.

### Steps to reproduce
Add this to a layout XML.
```
<com.mukesh.OtpView
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:focusableInTouchMode="true"
        android:textAllCaps="true"
        tools:text="LPHgd" />
```
### Expected behaviour
The text should be all caps
![Screenshot 2020-08-20 at 10 21 21](https://user-images.githubusercontent.com/10282350/90752134-ee74e500-e2ce-11ea-8988-1e8b06ff79ee.png)

### Actual behaviour
The text is not all caps 
![Screenshot 2020-08-20 at 10 20 00](https://user-images.githubusercontent.com/10282350/90752035-cab19f00-e2ce-11ea-9a2e-50321604715a.png)

**Comment by mukeshsolanki** [comment]
Fixed in ver 2.1.2
