### ISSUE TITLE
Keypad not showing up

### ISSUE THREAD

**Issue by tbkj98** [mukeshsolanki/android-otpview-pinview#109]
Hi,
I am using the library version 2.0.3
I just copied the code from README file, modified a couple of attributes and installed the app. But the keypad is not showing up after successful installation.

Here is the code snippet, i am using

<com.mukesh.OtpView
        android:id="@+id/otpEditText"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:inputType="number"
        android:textColor="@color/secondPrimary"
        app:OtpItemCount="@integer/max_otp_length"
        app:OtpLineColor="@color/secondPrimary"
        app:OtpViewType="line"
        app:layout_constraintBottom_toBottomOf="parent"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toTopOf="parent" />

**Comment by mukeshsolanki** [comment]
Have you added the style?

**Comment by mukeshsolanki** [comment]
@tbkj98 any update on this?
