### ISSUE TITLE
AAPT: error: attribute app:OtpItemCount not found.

### ISSUE THREAD

**Issue by ridamnibjia** [mukeshsolanki/android-otpview-pinview#113]
### Subject of the issue
OtpItemCount or any app:attribute doesn't work.

### Steps to reproduce
This is my code 
`<com.mukesh.OtpView
        android:id="@+id/otp_view"
        android:layout_centerHorizontal="true"
        android:OtpItemCount="5"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="72dp"
        android:inputType="number"
        android:itemBackground="@color/colorPrimary"
        android:textColor="@android:color/white"
        />`
Which is giving me this error:
`AAPT: error: attribute android:OtpItemCount not found.`

Please help!!!
### Expected behaviour
It should accept the attribute and work accordingly.

### Actual behaviour
Tell us what happens instead

**Comment by mukeshsolanki** [comment]
Which version of the lib are you using??

**Comment by mukeshsolanki** [comment]
You are using the wrong namespace please you app not android

**Comment by harshabhadra** [comment]
> 
> 
> You are using the wrong namespace please you app not android

I'm using app:itemCount="6" still getting same error

**Comment by Joseph-TSS** [comment]
use app:ItemCount

**Comment by Andromeda606** [comment]
I have the same problem.

**Comment by amit7127** [comment]
Yes with app namespace also, still facing the same issue.

**Comment by vinnykawa** [comment]
I'm using the app namespace and experiencing the same problem.

**Comment by abduqahhoruz** [comment]
I have the same error log... Why other libraries are working but not this one...

**Comment by Yash5454** [comment]
AAPT: error: attribute layout_MarginTop (aka com.example.project:layout_MarginTop) not found.
please give solution

**Comment by Andromeda606** [comment]
You can edit the java part, this seems to be the best solution for now

**Comment by mukeshsolanki** [comment]
Please check the latest version of the library.
