### ISSUE TITLE
AAPT: error: attribute not found

### ISSUE THREAD

**Issue by Andromeda606** [mukeshsolanki/android-otpview-pinview#119]
### Subject of the issue
Android resource linking failed

### Steps to reproduce
<com.mukesh.OtpView
                android:id="@+id/otp_view"
                android:layout_width="wrap_content"
                android:layout_height="wrap_content"
                android:layout_marginTop="72dp"
                android:inputType="number"
                android:itemBackground="@color/main_color"
                android:textColor="@android:color/white"
                app:OtpItemCount="6"
                app:ItemCount="@color/colorPrimary"
                app:OtpViewType="line"
                />

**Comment by mukeshsolanki** [comment]
stale
