### ISSUE TITLE
I can't write to the otpView view

### ISSUE THREAD

**Issue by Andromeda606** [mukeshsolanki/android-otpview-pinview#122]
### Subject of the issue
I added OtpView view, but when I try to write, I cannot write, setText etc works.

### Steps to reproduce
`otpView.setEnabled(true);
        otpView.setAnimationEnable(true);
        otpView.setItemCount(6);`
`<com.mukesh.OtpView
                    android:id="@+id/otp_view"
                    android:layout_width="wrap_content"
                    android:layout_height="wrap_content"
                    android:layout_gravity="center"
                    android:fontFamily="@font/montserrat_black"
                    android:itemBackground="@drawable/bloob_social"
                    android:textColor="@android:color/white" />`

**Comment by lsuski** [comment]
Could be related with https://github.com/mukeshsolanki/android-otpview-pinview/issues/111

**Comment by Andromeda606** [comment]
> [# 111](https://github.com/mukeshsolanki/android-otpview-pinview/issues/111) ile ilgili olabilir[](https://github.com/mukeshsolanki/android-otpview-pinview/issues/111)

no, didn't work

**Comment by knakul853** [comment]
Hi,
i am using this library for my project here i am getting the same issue. i can copy paste but can't write. i tried changing input type but that too didn't work.
Is it fixed ?

**Comment by lsuski** [comment]
Check this https://github.com/mukeshsolanki/android-otpview-pinview/issues/90

**Comment by Andromeda606** [comment]
I added` android:focusableInTouchMode="true"` and it worked for me too
