### ISSUE TITLE
app:OtpItemBackground is not found

### ISSUE THREAD

**Issue by emartynov** [mukeshsolanki/android-otpview-pinview#124]
### Subject of the issue
Can not build the project

### Steps to reproduce
Use 2.1.2 version add `app:OtpItemBackground` as you read in the README.

### Expected behaviour
Project builds.

### Actual behaviour
Project build fails.

I see that in sources `android:itemBackground` is still used.

**Comment by mukeshsolanki** [comment]
Please check the latest version of the library.
