### ISSUE TITLE
OtpView is not gaining focus and not showing keypad 

### ISSUE THREAD

**Issue by arunp1024** [mukeshsolanki/android-otpview-pinview#125]
<com.mukesh.OtpView
            android:id="@+id/otp_view"
            android:layout_width="wrap_content"
            android:layout_height="50dp"
            android:inputType="number"
            android:layout_marginTop="@dimen/margin_32"
            android:textColor="@android:color/white"
            app:OtpItemWidth="40dp"
            app:OtpItemCount="6"
            app:OtpLineColor="@color/white"
            app:OtpViewType="none"
            android:clickable="true"
            android:textIsSelectable="true"
            android:focusable="true"
            android:cursorVisible="true"
            android:focusableInTouchMode="true"
            app:layout_constraintStart_toStartOf="@id/guideline2"
            app:layout_constraintTop_toBottomOf="@+id/enter_otp_txt"
            app:layout_constraintEnd_toEndOf="@+id/guideline3"
            />
I'm using above xml and below style

  <style name="AppTheme" parent="Theme.MaterialComponents.Light.DarkActionBar">
        
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="otpViewStyle">@style/OtpWidget.OtpView</item>

    </style>
    
    But otpview is not getting focus.

In some devices its not working and in some devices its working
Working in Mi A2.
Not working in Nokia 7.1 and One plus 5T

Expected to show keyboard with otpview focused in all devices

**Comment by gokul1408** [comment]
Add otpview style in the AppTheme

  <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    
    <item name="otpViewStyle">@style/OtpWidget.OtpView</item>
  </style>

**Comment by Sushantlama** [comment]
still not working .
 @gokul1408 please be more specific on how to use that style.
whose style attribute should be that 
Android manifest or main layout or the otp view 
i tried all three .nothing is working.

**Comment by Sushantlama** [comment]
@gokul1408  Thanks it worked well

**Comment by AdieOlami** [comment]
I am experiencing this and I have done what was specified here.

**Comment by arzakmiftakhul** [comment]
add android:focusableInTouchMode="true" on OtpView

**Comment by todojean** [comment]
Ao colocar o codigo abaixo no "on code sent" o teclado aparece mas o OTP view não recebe o foco.
        InputMethodManager imm = (InputMethodManager) getSystemService(Context.INPUT_METHOD_SERVICE);
        imm.toggleSoftInput(InputMethodManager.SHOW_FORCED,0);
        binding.otpView.requestFocus();

Não Achei a solução ainda.

**Comment by haissamtariqzaman** [comment]
> android:focusableInTouchMode="true"

Thankyou so much

**Comment by absolute-vijju** [comment]
**1. Add this property (android:windowSoftInputMode="stateVisible") into your manifest's activity tag like this:**

`<activity
            android:name=".ui.AuthActivity"
            android:exported="true"
            android:screenOrientation="portrait"
            android:windowSoftInputMode="stateVisible" />`

**2. Add this line into your Activity class when you want to open keyboard:**

`mBinding.otpView.requestFocus()`

_That's all you need to do :)_
