### ISSUE TITLE
Can't focus the cursor on any item other than the first item without entering the code

### ISSUE THREAD

**Issue by doannguyenhat** [mukeshsolanki/android-otpview-pinview#126]
I want to focus cursor to any item when I not enter code yet, but I can't, you can help me support for this issue, please?

**Comment by avocadochif** [comment]
Hi)
any updates about this issue?

**Comment by dishankEbizz** [comment]
i have same, can you help me

**Comment by mukeshsolanki** [comment]
That does not look like something we would want to implement. What would the user want to head over to the second digint without entering the first?
