### ISSUE TITLE
PinView  is not showing in my layout please help me bro

### ISSUE THREAD

**Issue by usamaluckyofficiall** [mukeshsolanki/android-otpview-pinview#128]
### Subject of the issue
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by usamaluckyofficiall** [comment]
bro kindly help me

**Comment by BlacKDevil-ops** [comment]
Same problem I face if you have solution please share with me

**Comment by mukeshsolanki** [comment]
Can you please share the sample of the code.
