### ISSUE TITLE
it is not even syncing in my gradle file

### ISSUE THREAD

**Issue by OmPatel212** [mukeshsolanki/android-otpview-pinview#130]
i have included:-
                    maven { url "https://jitpack.io" } in repository
and 
                     implementation 'com.github.mukeshsolanki:android-otpview-pinview:2.1.2' in dependencies 

but it is not at all be able for syncing 

I doubt that is this library still working?.......

**Comment by komal-30** [comment]
> i have included:- maven { url "https://jitpack.io" } in repository and implementation 'com.github.mukeshsolanki:android-otpview-pinview:2.1.2' in dependencies
> 
> but it is not at all be able for syncing
> 
> I doubt that is this library still working?.......

I am facing the same issue

**Comment by sirqoharastus** [comment]
Me three

**Comment by radha-panda** [comment]
I too had this issue 
by adding 
        maven { url 'https://jitpack.io' }
the above line in my settings.gradle 
under the repositories model did the work for me

**Comment by OmPatel212** [comment]
solution 1) in my case i was putting the dependencies on project level gradle file but it fixed when i added it in module level build.gradle file 

solution 2) if the error still remains then add the maven{url  'https://jitpack.io'} in the settings.gradle file below mavenCentral or below jcenter 

solution 3)if it still remains unsolved then in settings.gradle file comment out dependencyResolutionManagement{ } whole code block and in build.gradle project level file add all{} covering the whole block of buildscript 
all{
  buildscript {
      repositories {
          google()
          jcenter()
          maven{url 'https://jitpack.io'}
      }
      dependencies {
          classpath "com.android.tools.build:gradle:7.0.0"
          
          // NOTE: Do not place your application dependencies here; they belong
          // in the individual module build.gradle files
      }
  }
}



this will solve your problem
