### ISSUE TITLE
GRADLE BUILD IS FAILING!

### ISSUE THREAD

**Issue by Sallubhau** [mukeshsolanki/android-otpview-pinview#131]
### Subject of the issue
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by radha-panda** [comment]
I too had this issue
by adding
maven { url 'https://jitpack.io' }
the above line in my settings.gradle
under the repositories model did the work for me
