### ISSUE TITLE
Size of pin Box is fixed not increasing 

### ISSUE THREAD

**Issue by LuckyBuyAsif** [mukeshsolanki/android-otpview-pinview#133]
### Subject of the issue
Size of pin Box is not increasing 

### Steps to reproduce
I have update the size of width and height of box inside dimens folder but still the size is same I have implemented pinview inside dialogFragment
### Expected behaviour
Size should be increase
### Actual behaviour
Tell us what happens instead

**Comment by mukeshsolanki** [comment]
Please try the new version. There is a property call `containerSize` That can help in giving the size for the container.
