### ISSUE TITLE
OtpView new 2.1.2 version is error 

### ISSUE THREAD

**Issue by Badshah172** [mukeshsolanki/android-otpview-pinview#134]
### Subject of the issue
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by Badshah172** [comment]
OtpView 2.1.2 new version is error  please send update version

**Comment by Axisvation** [comment]
yes
