### ISSUE TITLE
Class referenced in the layout file, `com.mukesh.OtpView`, was not found in the project or the libraries

### ISSUE THREAD

**Issue by SakshamYadav31202** [mukeshsolanki/android-otpview-pinview#137]
### Subject of the issue
Describe your issue here.

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by Prathyushakamineni** [comment]
Getting this error. How to rectify it?
Can anyone help me ?

**Comment by mukeshsolanki** [comment]
Please try the latest version. The new version is made with compose. Please check the updated read me to see how to implement the new version
