### ISSUE TITLE
AAPT: error: attribute layout_marginTop (aka com.example.project:layout_marginTop) not found.

### ISSUE THREAD

**Issue by Yash5454** [mukeshsolanki/android-otpview-pinview#139]
<EditText
        android:id="@+id/email"
        android:layout_width="0dp"
        android:layout_height="wrap_content"
        android:layout_marginTop="28dp"
        android:background="@drawable/edit_text_bg"
        android:drawableLeft="@drawable/ic_baseline_account_circle"
        android:drawablePadding="10dp"
        android:elevation="3dp"
        android:hint="Email"
        android:padding="15dp"
        app:layout_marginTop="10dp"
        app:layout_constraintEnd_toEndOf="parent"
        app:layout_constraintStart_toStartOf="parent"
        app:layout_constraintTop_toBottomOf="@+id/textView"
        app:layout_constraintWidth_percent=".8"
        app:layout_gonemarginTop="30dp" />

**Comment by mukeshsolanki** [comment]
Please try the latest version
