### ISSUE TITLE
com.mukesh.OtpView not recogniz

### ISSUE THREAD

**Issue by anuragsingh23** [mukeshsolanki/android-otpview-pinview#140]
Class referenced in the layout file, com.mukesh.OtpView, was not found in the project or the libraries
Cannot resolve class com.mukesh.OtpView 

I already added  
maven { url 'https://jitpack.io' }
implementation 'com.github.mukeshsolanki:android-otpview-pinview:2.1.2'

**Comment by sakib556** [comment]
i have the same problem

**Comment by Riftar** [comment]
add it at `settings.gradle`. Already answered [here](https://github.com/mukeshsolanki/android-otpview-pinview/issues/82)

**Comment by mukeshsolanki** [comment]
Please try the latest version.
