### ISSUE TITLE
Anyway to separate the border color and text color?

### ISSUE THREAD

**Issue by shafayatb** [mukeshsolanki/android-otpview-pinview#145]
Hello, I am using the latest version of the library and charColor changes both border color and character color. Any way to change this?

<img src="https://user-images.githubusercontent.com/20676587/167921710-5180ac7c-0d28-48a4-9037-b69ab6da2a95.png" data-canonical-src="https://user-images.githubusercontent.com/20676587/167921710-5180ac7c-0d28-48a4-9037-b69ab6da2a95.png" width="560" height="1120" />

Or can we increase container size when `type = OTP_VIEW_TYPE_NONE` is set?

<img src="https://user-images.githubusercontent.com/20676587/167922009-75bc6208-779c-489d-a45e-3e4ee3b7c449.png" data-canonical-src="https://user-images.githubusercontent.com/20676587/167922009-75bc6208-779c-489d-a45e-3e4ee3b7c449.png" width="560" height="1120" />

**Comment by ajitesh-entellus** [comment]
I'm also facing this issue

**Comment by sakarayajitesh** [comment]
I'm also facing the exact issue

**Comment by Avishek1989** [comment]
Please solve this issue ASAP @mukeshsolanki
