### ISSUE TITLE
I can’t able to type anything into OTPview

### ISSUE THREAD

**Issue by reenasavaliya21** [mukeshsolanki/android-otpview-pinview#151]
I can't able to type into otpview

**Comment by pravinsphinx** [comment]
@mukeshsolanki Getting same issue

**Comment by kirti-7** [comment]
> I can't able to type into otpview

I got an error 
Failed to resolve: com.github.mukeshsolanki.android-otpview-pinview:otpview:3.1.0
Do you know how to resolve it?

**Comment by kirti-7** [comment]
> @mukeshsolanki Getting same issue

could you please help solving this error
Failed to resolve: com.github.mukeshsolanki.android-otpview-pinview:otpview:3.1.0

**Comment by baymax1234** [comment]
Same issue

**Comment by kirti-7** [comment]
> Same issue
Try this:-
https://github.com/ChaosLeung/PinView
Watch the tutorial, it works:-
https://youtu.be/WdOSbWEBYZQ

**Comment by SubhankarCodeGeek** [comment]
add this within your OtpView

android:focusableInTouchMode="true" 

you'll be able to interact with it. @reenasavaliya21 @mukeshsolanki

**Comment by OmarAbuShanb** [comment]
> add this within your OtpView
> 
> android:focusableInTouchMode="true"
> 
> you'll be able to interact with it. @reenasavaliya21 @mukeshsolanki

Nice, it works fine
