### ISSUE TITLE
1.0.5 not working

### ISSUE THREAD

**Issue by Mayur-007** [mukeshsolanki/android-otpview-pinview#16]
Implemented with dependency 1.0.5 and tried for appx 2 hours but the screen was blank, wasn't able to see anything then I changed it to 1.0.4 and It was working fine.

Please check the same.

**Comment by mukeshsolanki** [comment]
Have you added  `app:length="4"`to the XML view? You can take a look at the example app for more details

**Comment by Mayur-007** [comment]
Yes, I have added and checked.
It's still giving no output.

It also don't show preview in layout.
while it does in 1.0.4

**Comment by mukeshsolanki** [comment]
@Mayur-007 can you share a bit of code snippet or the error log

**Comment by Mayur-007** [comment]
**Layout**

```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto"
    xmlns:tools="http://schemas.android.com/tools"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:gravity="center_horizontal"
    android:orientation="vertical" >
  <com.mukesh.OtpView
      android:id="@+id/otp_view"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:inputType="number"
      app:length="3" />
</LinearLayout>
```

**Java**

```
private OtpView mOtpView;
mOtpView = findViewById(R.id.otp_view);
```

**Comment by mukeshsolanki** [comment]
@Mayur-007 this seems to be weird as the exact same thing is working in the example app. I'm not able to reproduce the issue can you share a simple example app with the issue?

**Comment by Mayur-007** [comment]
I think if you create a new project and compile it with this version instead of using your local lib project,
you will get the idea.

**Comment by mukeshsolanki** [comment]
@Mayur-007  it seems to be working fine even on a standalone project not sure why it seems to fail for you. We have just release 1.0.6 can you use that and see if the problem still persists.

**Comment by Mayur-007** [comment]
![otpview](https://user-images.githubusercontent.com/16119787/39754054-8cb784da-52de-11e8-88c4-76aff33e74f8.JPG)


It looks weird.
I changed it to 1.0.6, it worked but UI is so strange. It's long edit text fields and I cant type anything in it.
also app:otp="1234" is compulsory.
What if I wanna leave it blank and fill manually or automatically when I get the OTP SMS?

**Comment by mukeshsolanki** [comment]
Thanks for pointing out we found a crash and will fix it asap

**Comment by Mayur-007** [comment]
Thanks, I can help if you want.

**Comment by mukeshsolanki** [comment]
we are planning a release with `1.1.0` which will have a bunch of changes we'll merge this into it as well

**Comment by mukeshsolanki** [comment]
@Mayur-007 can you try version `1.1.0` and check if it still breaks?

**Comment by mukeshsolanki** [comment]
@Mayur-007 any update?

**Comment by Mayur-007** [comment]
Hello, Bit busy in some work.
Will check soon and will get back to you as soon as possible.
