### ISSUE TITLE
Set custom OTP count

### ISSUE THREAD

**Issue by omkar243** [mukeshsolanki/android-otpview-pinview#17]
How to add OTP count in OTP view.
it takes default 4 numbers but I want 6 numbers in OTP.

**Comment by mukeshsolanki** [comment]
add `app:length="4"` to your xml view

**Comment by omkar243** [comment]
I tried this but it shows error 

> error: attribute 'mypackagename:length' not found.

my code

```
  <com.mukesh.OtpView
                android:id="@+id/otp_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content"
                android:layout_marginBottom="42dp"
                android:inputType="number"
                app:otp="-"
                app:length="6"
                android:textColor="#fff"/>
```

**Comment by omkar243** [comment]
Issue Resolved !
error belongs to dependency version I used old version **1.0.2**
app:length="6" 
working in latest version **1.0.5**

**Comment by mukeshsolanki** [comment]
okay thanks for the update
