### ISSUE TITLE
Changing textsize

### ISSUE THREAD

**Issue by harini9804** [mukeshsolanki/android-otpview-pinview#22]
How to change the size of the number input in the otp view? The parameters app:width, app:height have no effect on this.

**Comment by deepaksachdeva** [comment]
@harini9804 You can also change height, width, and spacing by changing in the method "generateViews" in OtpView class.
For Number input, you can use app:length attribute in your xml. 

```
  <com.mukesh.OtpView
      android:id="@+id/otp_view"
      android:layout_width="wrap_content"
      android:layout_height="wrap_content"
      android:inputType="number"
      app:length="6" // set number of input
      >
```

**Comment by mukeshsolanki** [comment]
can you try the latest version `2.0.0` and simply set the size using `textsize`
