### ISSUE TITLE
unable to integrate app in project

### ISSUE THREAD

**Issue by twitu** [mukeshsolanki/android-otpview-pinview#23]
`implementation 'com.github.mukeshsolanki:android-otpview-pinview:<latest-version>'`  gives error `Failed to resolve: com.github`

`implementation 'com.github.mukeshsolanki:android-otpview-pinview:1.1.0'` gives error `Failed to resolve: com.github.mukeshsolanki:android-otpview-pinview:1.1.0`

**Comment by tobiasschuerg** [comment]
You probably need to add the jitpack repository.

**Comment by ghost** [comment]
Added jitpack rep and still didn't work

**Comment by mukeshsolanki** [comment]
can you share the build.gradle from the project root and the app module?
