### ISSUE TITLE
How to increase text size of mumber password input type ? 

### ISSUE THREAD

**Issue by Jay268** [mukeshsolanki/android-otpview-pinview#25]
Hi @mukeshsolanki 

I have been implementing through your library. Everything seems to be working perfect.

I have one query is their any possibility to be increase `TextSize` i mean i am using `numberPassword` and i wanted dots to be look more bigger then default.

Can you able to check if we can add *TextSize* property in same.

Is their any possibility you can look into this ? it will be great!!

**Comment by deepaksachdeva** [comment]
@Jay268 Simply add below line in the for loop of "generateViews" method in **OtpView class**.

editText.setTextSize(/*set size here**/);
for example:
editText.setTextSize(20.0f);
