### ISSUE TITLE
The View does not fit if app length is more than 6

### ISSUE THREAD

**Issue by BraveEvidence** [mukeshsolanki/android-otpview-pinview#26]
Hi,

I want the app length to be 10.If I increase the app:length attribute to 10 the view does not fit and I can see only 6 boxes. Let me know if there is any work around?

**Comment by deepaksachdeva** [comment]
@PritishSawant Have a look this, it may help you.

Replace:

 ```
LinearLayout.LayoutParams params =
          new LinearLayout.LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT);
```
To:

```
 LinearLayout.LayoutParams params =
          new LinearLayout.LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT, 1.0f);
```

**Comment by BraveEvidence** [comment]
@deepaksachdeva does not work.

**Comment by deepaksachdeva** [comment]
@PritishSawant Still fields are not in a single row or you are not able to see the entered text now. Please send me your screenshot too.

**Comment by BraveEvidence** [comment]
@deepaksachdeva 
![screen shot 2018-07-27 at 7 28 15 am](https://user-images.githubusercontent.com/24708929/43297436-fbb73550-916e-11e8-9c26-4315beb7b47f.png)


This is the xml

` <com.mukesh.OtpView
        android:id="@+id/otp_view"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_marginEnd="8dp"
        android:layout_marginStart="8dp"
        android:layout_marginTop="8dp"
        android:background="#cccccc"
        android:inputType="number"
        app:otp="1234567890"
        android:textColor="@color/colorPrimary"
        app:length="10" />`

This is the change which you told me to make

LinearLayout.LayoutParams params =
                    new LinearLayout.LayoutParams(LayoutParams.WRAP_CONTENT, LayoutParams.WRAP_CONTENT,1.0f);

**Comment by mukeshsolanki** [comment]
have you tried `app:space` to reduce the space between digits?

**Comment by BraveEvidence** [comment]
@mukeshsolanki does not work

**Comment by mukeshsolanki** [comment]
@PritishSawant can you try the latest version `2.0.0`

**Comment by BraveEvidence** [comment]
I tried with version 2 and the max it can fit is 8 with no margins on Start and End even after adding margins
![screen shot 2018-08-28 at 8 11 08 am](https://user-images.githubusercontent.com/24708929/44697559-f90e9200-aa99-11e8-898c-2334c1831039.png)

**Comment by mukeshsolanki** [comment]
that depends on the screen size im afraid that's the limit for now

**Comment by pravingaikwad07** [comment]
For otpLength = n  (where n is any number) , try this:

Kotlin code:

```
val otp_view = findViewById<OtpView>(R.id.otp_view)
otp_view.getViewTreeObserver()
            .addOnPreDrawListener(object : ViewTreeObserver.OnPreDrawListener {
                override fun onPreDraw(): Boolean {
                    if (otp_view.getViewTreeObserver().isAlive()) otp_view.getViewTreeObserver()
                        .removeOnPreDrawListener(this)
                    val viewWidth = otp_view.width
                    val otpCount = otp_view.itemCount //this is otp length lets say 8

                    otp_view.itemWidth = (viewWidth / otpCount) - (otp_view.itemSpacing)

                  //  Log.d(TAG, "onPreDraw: $viewWidth :: $otpCount :: ${otp_view.itemWidth}")

                    return true
                }
            })
```
