### ISSUE TITLE
setOnFocusChangeListener Method is not working in android.

### ISSUE THREAD

**Issue by pinal-dhaduk** [mukeshsolanki/android-otpview-pinview#28]
i want one view visible when i focus on otpView. and view disable when i focus off otpView.

my Code is

        otpView.setOnFocusChangeListener(new View.OnFocusChangeListener() {
            @Override
            public void onFocusChange(View view, boolean b) {
                if (b) {
                    showImageVisibleView();
                    } else {
                    showImageInvisibleView();
                    }
                }
            }
        });
Give here answer if as soon as possible.

**Comment by mukeshsolanki** [comment]
can you try the latest version `2.0.0`
