### ISSUE TITLE
Its very slow

### ISSUE THREAD

**Issue by sagarzala123** [mukeshsolanki/android-otpview-pinview#3]
When I typing its not type words, skips some words while typing. So its very slow.

**Comment by mukeshsolanki** [comment]
Seems to be a strange issue not sure why that would happen can you please try it on another device??

**Comment by mukeshsolanki** [comment]
@sagarzala123 can you please check again??

**Comment by sagarzala123** [comment]
I checked in another device. It's working fast.

But in my Samsung J7, it working slow.

**Comment by mukeshsolanki** [comment]
hmmm strange I've tested on a number of devices 

1. Pixel
2. Nexus 6p
3. Samsung Duos
4. Micromax Canvas Lite
5. Oneplus 2

Seems fine on them. I'm calling it a device issue.
