### ISSUE TITLE
cannot find symbol method otpView.getText() and otpView.setOtpCompletionListener(this)

### ISSUE THREAD

**Issue by skillFocus16** [mukeshsolanki/android-otpview-pinview#35]
Trying to compile project but build failing with errors: cannot find symbol method otpView.getText() and otpView.setOtpCompletionListener(this) in my activity 

added implementation 'com.mukesh:otpview:1.0.1',  maven repository and interface OnOtpCompletionListener

**Comment by mukeshsolanki** [comment]
Your using the wrong version of the library the latest version is 2.0.0

**Comment by skillFocus16** [comment]
It worked after I changed dependency from **implementation 'com.mukesh:otpview:1.0.1'** to **implementation 'com.github.mukeshsolanki:android-otpview-pinview:2.0.0'** .. changing to **implementation 'com.mukesh:otpview:2.0.0'** doesn't work. Thanks, Mukesh!

**Comment by Manasvi-Pundir** [comment]
can not find method otpview.setListner(), if i am using otpview.setOncompletionListner() it crashes all the time, dependency i am using implementation 'com.github.mukeshsolanki:android-otpview-pinview:2.0.3'.
