### ISSUE TITLE
Font Family - Not Updating

### ISSUE THREAD

**Issue by yokeshezumalai** [mukeshsolanki/android-otpview-pinview#37]
I have tried to update the font family, its not getting updated. Is that possible?

<style name="OtpWidget.OtpView" parent="Widget.AppCompat.EditText">
        <item name="android:textSize">18sp</item>
        <item name="android:fontFamily">@font/the_sans_arabic_plain</item>
        <item name="android:background">#FFFFFF</item>
    </style>

**Comment by daupawar** [comment]
This solution Worked for me  

```
<style name="OtpWidget.OtpView" parent="Widget.AppCompat.EditText">
        <item name="android:fontFamily">@font/js_light</item>
</style>
```
