### ISSUE TITLE
OtpView is not gaining focus and not showing keypad.

### ISSUE THREAD

**Issue by shashank0708** [mukeshsolanki/android-otpview-pinview#38]
I am using the latest version of  `OtpView` and here is my code:-

`  <com.mukesh.OtpView
            android:id="@+id/otp_view"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:inputType="number"
            android:textColor="@android:color/white"
            app:itemCount="4"
            app:lineColor="@color/colorPrimaryDark"
            app:viewType="line"
            app:itemSpacing="25dp"
            app:hideLineWhenFilled="true"
            />`
I don't know what is happening but somehow keypad is not opening for typing,I think the recent update you have done 20 days ago has something to do with this BUG.

**Comment by dineshmm23** [comment]
<com.mukesh.OtpView
        android:id="@+id/et_login_pairing"
        android:layout_width="wrap_content"
        android:layout_height="wrap_content"
        android:layout_marginTop="72dp"
        android:itemBackground="@color/colorPrimary"
        android:textColor="@android:color/black"
        app:itemCount="6"
        app:lineColor="@color/colorPrimary"
        app:viewType="line" />

same here

**Comment by Subarekha** [comment]
Hi Guys,
Any solution to this

**Comment by Subarekha** [comment]
Here is the solution
https://github.com/mukeshsolanki/android-otpview-pinview/issues/39

**Comment by mukeshsolanki** [comment]
Adding  ``` <item name="otpViewStyle">@style/OtpWidget.OtpView</item>``` to you AppTheme should fix the issue

**Comment by shahzadafridi** [comment]
> Adding ` <item name="otpViewStyle">@style/OtpWidget.OtpView</item>` to you AppTheme should fix the issue

It works. Thanks to mukeshsolanki!
