### ISSUE TITLE
Keyboard is not showing

### ISSUE THREAD

**Issue by qburst-alexj** [mukeshsolanki/android-otpview-pinview#39]
As per the example you provided, the keyboard is not showing to type.

`        <com.mukesh.OtpView
            android:id="@+id/otp_view"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_below="@id/input_layout"
            android:layout_marginTop="@dimen/dimen_16dp"
            android:inputType="number"
            android:layout_centerHorizontal="true"
            android:textColor="@android:color/white"
            app:itemCount="4"
            android:focusable="true"
            app:lineColor="@color/colorPrimary"
            app:viewType="line"
            android:cursorVisible="true"
            />
`

**Comment by ezamelczyk** [comment]
There is a workaround for that.

In your main app theme set attribute

```
<style name="AppTheme">
    ...
    <item name="otpViewStyle">@style/OtpWidget.OtpView</item>
</style>

<style name="OtpWidget.OtpView" parent="Widget.AppCompat.EditText">
    <item name="android:background">@null</item>
    <item name="android:minHeight">0dp</item>
    <item name="android:maxLines">1</item>
  </style>
```

**Comment by waseem786** [comment]
@ezamelczyk's solution works, thanks :)

**Comment by Subarekha** [comment]
Superb.. Thanks

**Comment by mayankkussh** [comment]
i am unable to use @ezamelczyk solution, getting the error "style attribute \u0027attr/otpViewStyle" not found. Any help will be appreciated

**Comment by pratikbutani** [comment]
> There is a workaround for that.
> 
> In your main app theme set attribute
> 
> ```
> <style name="AppTheme">
>     ...
>     <item name="otpViewStyle">@style/OtpWidget.OtpView</item>
> </style>
> 
> <style name="OtpWidget.OtpView" parent="Widget.AppCompat.EditText">
>     <item name="android:background">@null</item>
>     <item name="android:minHeight">0dp</item>
>     <item name="android:maxLines">1</item>
>   </style>
> ```

Do we have to set anything in OTP View?

**Comment by pratikbutani** [comment]
> There is a workaround for that.
> 
> In your main app theme set attribute
> 
> ```
> <style name="AppTheme">
>     ...
>     <item name="otpViewStyle">@style/OtpWidget.OtpView</item>
> </style>
> 
> <style name="OtpWidget.OtpView" parent="Widget.AppCompat.EditText">
>     <item name="android:background">@null</item>
>     <item name="android:minHeight">0dp</item>
>     <item name="android:maxLines">1</item>
>   </style>
> ```

I got issue If I am setting only in `style.xml`
You have to do this thing for both, `values/style.xml` and `values-v21/style.xml`

**Comment by mukeshsolanki** [comment]
Adding  ``` <item name="otpViewStyle">@style/OtpWidget.OtpView</item>``` to you AppTheme should fix the issue

**Comment by pratikbutani** [comment]
> Adding ` <item name="otpViewStyle">@style/OtpWidget.OtpView</item>` to you AppTheme should fix the issue

It's working.

**Comment by md-rifatkhan** [comment]
Not working for me 😥

**Comment by Mohamed-samir03** [comment]
android:focusable="true"
android:focusableInTouchMode="true"
android:clickable="true"

- You should add this.

**Comment by rranjithkumar100** [comment]
they set text color white, change the text color to black 

                android:textColor="@color/black"

**Comment by lalit-iottive** [comment]
> android:focusable="true" android:focusableInTouchMode="true" android:clickable="true"
> 
> * You should add this.

thanks @rranjithkumar100
