### ISSUE TITLE
Backpress dont works 

### ISSUE THREAD

**Issue by Khurriazafar55** [mukeshsolanki/android-otpview-pinview#4]
When i use this library, everythings works perfectly but not the Backpress key.. What should i do for this?

**Comment by mukeshsolanki** [comment]
By back press you mean the hardware back button?? If so then it something you will need to handle. Fyi I don't seen any one using the back button to clear data.

**Comment by mukeshsolanki** [comment]
@hoori55 can you please respond?

**Comment by Khurriazafar55** [comment]
Actually i am using your library for setting a pin code, i have solved my
backpress issue now.. Sorry for answering you late
Thanks once again :)
