### ISSUE TITLE
Cant enter OTP manually

### ISSUE THREAD

**Issue by droid-lover** [mukeshsolanki/android-otpview-pinview#40]
No functionalities to enter otp manually

**Comment by mukeshsolanki** [comment]
What are you trying to do?

**Comment by kowchong** [comment]
@mukeshsolanki  I think he mean the keyboard didn't show up.

**Comment by neilharia7** [comment]
@kowchong @myJarvis If that's the case then just set 
`android:focusableInTouchMode="true"` 
`android:focusable="true"`

**Comment by mukeshsolanki** [comment]
can you give more details like how you are creating the xml?

**Comment by mukeshsolanki** [comment]
Adding  ``` <item name="otpViewStyle">@style/OtpWidget.OtpView</item>``` to you AppTheme should fix the issue

**Comment by CleatonPais** [comment]
> @kowchong @myJarvis If that's the case then just set
> `android:focusableInTouchMode="true"`
> `android:focusable="true"`

This worked for me along with the changes in style.xml and the dependencies
