### ISSUE TITLE
support for asterisk(*)

### ISSUE THREAD

**Issue by naikdp7** [mukeshsolanki/android-otpview-pinview#46]
it is very useful if you provide attribute for setting up asterisk(*)

**Comment by MukeshGreenDeveloper** [comment]
u mean like characters as astrisk(*)
****
----

**Comment by naikdp7** [comment]
yes when inputype is Password

**Comment by mukeshsolanki** [comment]
we could do this but haven't seen anyone asking for it. May added it later
