### ISSUE TITLE
Can't enter values, It's unclickable!

### ISSUE THREAD

**Issue by xSuperMu** [mukeshsolanki/android-otpview-pinview#47]

**Comment by mukeshsolanki** [comment]
Have you added the styles as mentioned here https://github.com/mukeshsolanki/android-otpview-pinview#how-to-use-the-library

**Comment by cyph3rcod3r** [comment]
Can you tell us what exactly is needed to make it clickable I have just set the view in xml and it is visible in the activity but its not clickable and focusable.

**Comment by mukeshsolanki** [comment]
add `<item name="otpViewStyle">@style/OtpWidget.OtpView</item>` to your default app theme in the styles.xml

**Comment by softmarshmallow** [comment]
@mukeshsolanki  Thanks!
