### ISSUE TITLE
Clear codes

### ISSUE THREAD

**Issue by CarlyAdam** [mukeshsolanki/android-otpview-pinview#50]
### Subject of the issue
@mukeshsolanki  First of all thanks for this amazing library....good work!!
How I can clear all codes ??
Thanks again ;)

**Comment by mukeshsolanki** [comment]
simply try otpview.setText("")

**Comment by CarlyAdam** [comment]
Yes it's the way, but after reset all codes i couldn't enter it again , so if i just add this  line "android:focusableInTouchMode="true"" the problem is solve. Thanks again
