### ISSUE TITLE
Delete Issue

### ISSUE THREAD

**Issue by riddhishahts** [mukeshsolanki/android-otpview-pinview#52]
Hi, your lib is good but I am not getting any call back when the user has deleted all the otp content. You should send the call back on your setOtpCompletionListener. 

Try to add OTP and then backspace/Delete them. You won't get any call back from it. I want to check that user has entered OTP or not.

**Comment by mukeshsolanki** [comment]
you can simply do otpView.getText() to get the text the user has entered. If it does not match the size then the user has not entered it.

**Comment by mukeshsolanki** [comment]
That should solve the problem let me know otherwise @riddhishahts if there is any specific reason as to why you need a listener for that.

**Comment by umeshkumar1990** [comment]
I need to disable verify button if otpview is not completed. On complete I enable verify button but in case if user completed otpview and delete some digits i need to disable it again then what to do.

**Comment by mukeshsolanki** [comment]
you can use an rx observable to do that. It would simply not make sense to add the incomplete listener since it would constantly keep firing everytime you enter a value.

**Comment by Aminul-Haque-Aome** [comment]
Can you give me the code to add Rx in the listener
