### ISSUE TITLE
Direction issue in arabic

### ISSUE THREAD

**Issue by umeshkumar1990** [mukeshsolanki/android-otpview-pinview#53]
### Subject of the issue
In arabic OTP view should start from right to left.

### Steps to reproduce
Change language from english to arabic.

### Expected behaviour
It should start from right to left in arabic.

### Actual behaviour
It's starting from left to right in arabic.

**Comment by aantoniv** [comment]
I also need the right to left textDirection feature. I've tried to use `android:textDirection="rtl"` or         `android:gravity="right"` but it does not work correctly with OtpView.  @mukeshsolanki Any chances to fix that ?

**Comment by umeshkumar1990** [comment]
@aantoniv yes i found the solution for that. Just use android:scaleX="-1" in case of arabic and "1" in case of english. It will work according to language.

**Comment by aantoniv** [comment]
@umeshkumar1990 I think, that is not exactly what I need :( Probably I mixed two issues.... One regarding arabic language, and other about RTL text direction.
If you check usual AppCompatEditText with `android:gravity="right"` , you'll see what I am trying to achieve

**Comment by mukeshsolanki** [comment]
@aantoniv I'm held up with other tasks at moment and would probably fix that in the future release but feel free to create a PR for it

**Comment by mukeshsolanki** [comment]
fixed in the latest version

**Comment by khan807** [comment]
how to change the otpview from ltr to rtl direction programatically? @mukeshsolanki
