### ISSUE TITLE
Does this library work in kotlin?

### ISSUE THREAD

**Issue by okeetris** [mukeshsolanki/android-otpview-pinview#58]
I am trying to integrate this into my Kotlin app and can create the view but can not press on the boxes to enter input or assign a listener properly. I have followed the instructions on the read-me exactly and am presuming it is a kotlin to java issue?

**Comment by okeetris** [comment]
I am trying to integrate this into my Kotlin app and can create the view but can not press on the boxes to enter input or assign a listener properly. I have followed the instructions on the read-me exactly and am presuming it is a kotlin to java issue?

**Comment by mukeshsolanki** [comment]
Have you set the style to your default apptheme?

**Comment by therajanmaurya** [comment]
> Have you set the style to your default apptheme?

Thanks @mukeshsolanki Yes it worked. I set the theme 

``` <style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    <!-- Customize your theme here. -->
    <item name="otpViewStyle">@style/OtpWidget.OtpView</item>
  </style>```

and It's working fine.

**Comment by mukeshsolanki** [comment]
Sounds good closing the issue
