### ISSUE TITLE
Can't clear opt Values

### ISSUE THREAD

**Issue by sujanmt** [mukeshsolanki/android-otpview-pinview#59]
Can't clear opt ValuesDescribe your issue here.
If user wants to clear the opt value one by one  there is no listener for that

**Comment by mukeshsolanki** [comment]
there is no need for such a thing why would you need to a listener for a single event like clear or type. You can use a RxObservable for that

**Comment by vuhomobytelab** [comment]
@sujanmt 
When user correctly input value, but they remove some numbers, we will stuck with setOtpCompletionListener
So simple implement addTextChangedListener to listen every numbers that user input
