### ISSUE TITLE
AndroidX issue

### ISSUE THREAD

**Issue by FhdAlotaibi** [mukeshsolanki/android-otpview-pinview#60]
### OtpView not working
create new project and check on support androidX
add the gradle dependence of OtpView try to use it run the app it 's not working

**Comment by FhdAlotaibi** [comment]
just let OtpView extends androidx.appcompat.widget.AppCompatEditText instead of android.support.v7.widget.AppCompatEditText

**Comment by LowLowCoder-Mel** [comment]
Hi, I'm going to the library to upgrade to the androidx, 
``` 
    <!-- Base application theme. -->
    <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
        <!-- Customize your theme here. -->
        <item name="colorPrimary">@color/colorPrimary</item>
        <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
        <item name="colorAccent">@color/colorAccent</item>
        <item name="otpViewStyle">@style/OtpWidget.OtpView</item>
    </style>
```
To add this style it will work.

**Comment by idee24** [comment]
> Hi, I'm going to the library to upgrade to the androidx,
> 
> ```
>     
>     <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
>         
>         <item name="colorPrimary">@color/colorPrimary</item>
>         <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
>         <item name="colorAccent">@color/colorAccent</item>
>         <item name="otpViewStyle">@style/OtpWidget.OtpView</item>
>     </style>
> ```
> To add this style it will work.

Thanks alot.. This worked for me.

**Comment by asywalulfikri** [comment]
> Hi, I'm going to the library to upgrade to the androidx,
> 
> ```
>     
>     <style name="AppTheme" parent="Theme.AppCompat.DayNight.NoActionBar">
>         
>         <item name="colorPrimary">@color/colorPrimary</item>
>         <item name="colorPrimaryDark">@color/colorPrimaryDark</item>
>         <item name="colorAccent">@color/colorAccent</item>
>         <item name="otpViewStyle">@style/OtpWidget.OtpView</item>
>     </style>
> ```
> 
> To add this style it will work.

you save my life

**Comment by asterixorobelix** [comment]
The otpView does not register input from the soft keyboard on Android 9. Adding the otpViewStyle to the AppTheme also does not work. This is with OtpView 2.0.3

**Comment by iamareebjamal** [comment]
Bump

**Comment by JagadeeshBabuDamarasingu** [comment]
this issue still exists, keyboard not showing on click and no focus 

tried  <item name="otpViewStyle">@style/OtpWidget.OtpView</item> also, but doesn't work

not working in Redmi Note 4, os: 7.o(Nougat)

however working fine in Nokia 3.1( Android pie)

Update: otpView.setPadding(8, 0, 8, 0); making it unfocussable,

**Comment by aruns2896** [comment]
@FhdAlotaibi How to edit OtpView file because it is read-only file?

**Comment by iamareebjamal** [comment]
You can't. Fork the project or copy the code inside your project

**Comment by aruns2896** [comment]
So currently there's no any solution for this till now

**Comment by mukeshsolanki** [comment]
Will be fixed in the next version
