### ISSUE TITLE
Unable to paste code in otpview

### ISSUE THREAD

**Issue by jenistops** [mukeshsolanki/android-otpview-pinview#65]
I have tried copy code from SMS but I unable to paste the code in otpview.

**Comment by aligorithm** [comment]
I have this same issue. Is there a solution or fix yet?

**Comment by hosseiniSeyRo** [comment]
even i can not type any text in otp view!
i use android x, and add otp view to my project step by step

**Comment by avineetgupta** [comment]
I am also not able to even type anything. Can anyone help?

**Comment by sagaratalatti** [comment]
> even i can not type any text in otp view!
> i use android x, and add otp view to my project step by step

Any solution to this issue unable to type number into the OtpView with androidx

**Comment by faisalali1** [comment]
Dear all 
i'm also had stucked in this issue. then i simply add these 2 lines to otpView Xml 
        android:focusable="true"
        android:focusableInTouchMode="true"

its works for me. 
thanks

**Comment by sam43** [comment]
I am facing same problem, user can't paste the copied **OTP** from his message. Is there any ways to do that. Please let me know.
I have tried these so far:

        `
          <com.mukesh.OtpView
		android:id="@+id/otp_view"
		android:layout_width="wrap_content"
		android:layout_height="wrap_content"
		android:layout_marginStart="16dp"
		android:layout_marginTop="32dp"
		android:layout_marginEnd="16dp"
		android:focusableInTouchMode="true"
		android:cursorVisible="false"
		android:focusable="true"
		android:textIsSelectable="false"
		android:focusedByDefault="true"
		android:inputType="text"
		android:itemBackground="@color/colorTransparent"
		android:textColor="@color/colorPrimary"
		app:cursorColor="@color/colorPrimary"
		app:itemCount="6"
		app:itemSpacing="@dimen/margin8"
		app:layout_constraintEnd_toEndOf="parent"
		app:layout_constraintStart_toStartOf="parent"
		app:layout_constraintTop_toBottomOf="@+id/tv_number_to_send"
		app:lineColor="@color/colorPrimary"
		app:state_filled="true"
		app:viewType="line"
		tools:targetApi="o"
		/>`
