### ISSUE TITLE
How to set line color of filled input

### ISSUE THREAD

**Issue by Moseqi** [mukeshsolanki/android-otpview-pinview#66]
How to change color of the line when the field is filled. I have set the app:state_filled but the line is centered with  text

**Comment by nikhil001122** [comment]
@Moseqi Try to use this function :- 

    private void setLineColor(OtpView otpView) {
        int[][] states = new int[][]{
                new int[]{R.attr.state_filled},
                new int[]{-R.attr.state_filled}
        };

        int[] colors = new int[]{
                Color.parseColor("#FF0000"),              // filled color
                Color.parseColor("#FF00FF")              // unfilled color
        };

        ColorStateList colorsList = new ColorStateList(states, colors);
        otpView.setLineColor(colorsList);
    }
tested and works positively
