### ISSUE TITLE
Android resource compilation failed

### ISSUE THREAD

**Issue by asif4483** [mukeshsolanki/android-otpview-pinview#69]
### Android resource compilation failed
app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:4622: error: duplicate value for resource 'attr/viewType' with config ''.

app\build\intermediates\incremental\mergeDebugResources\merged.dir\values\values.xml:4622: error: resource previously defined here.

i am getting this two issue in my project

**Comment by sky9971** [comment]
Kindly provide any resolution on this, I'm also facing this issue.

**Comment by SSDABSiddique** [comment]
I am also facing this issue.
