### ISSUE TITLE
The First backspace press

### ISSUE THREAD

**Issue by beast-shubham** [mukeshsolanki/android-otpview-pinview#7]
Hi,
When I enter my 4 digit OTP code and click again on the last digit to delete a number, the cursor jumps back to the first number, (instead of remaining at the last number). 

Kindly let me know if there is some way to correct this issue. Thanks.

**Comment by beast-shubham** [comment]
Any updates?

**Comment by mukeshsolanki** [comment]
Can you share your code? the cursor stays at the last and does not jump to the first
