### ISSUE TITLE
setListener is not found in V-2.0.3 

### ISSUE THREAD

**Issue by Jenifer-Ramsingh** [mukeshsolanki/android-otpview-pinview#73]
### Subject of the issue
after integration the  V-2.0.3 the 
otpView.**setListener**(new OnOtpCompletionListener() {
            @Override public void onOtpCompleted(String otp) {
                // do Stuff
               Log.d("onOtpCompleted=>", otp);
            }
        });

**says** 

error: cannot find symbol
        otpView.setListener(new OnOtpCompletionListener() {
               ^

**Comment by yaroslavsudnik** [comment]
@Jenifer-Ramsingh please use **setOtpCompletionListener** instead of **setListener**
```java
private OtpView otpView;
 otpView = findViewById(R.id.otp_view);
 otpView.setOtpCompletionListener(new OnOtpCompletionListener() {
   @Override public void onOtpCompleted(String otp) {

     // do Stuff
     Log.d("onOtpCompleted=>", otp);
   }
 });
```

**Comment by Jenifer-Ramsingh** [comment]
Thanks @yaroslavsudnik  now working as expected.
