### ISSUE TITLE
How to add space between text input and keyboard?

### ISSUE THREAD

**Issue by meidikawardana** [mukeshsolanki/android-otpview-pinview#79]
My problem is similar to this issue: https://stackoverflow.com/questions/17630336/space-between-keyboard-and-edittext-in-android

but because this otpview has its own background, I cannot modify the background as I pleased.

Maybe you should add one more attribute like app:distanceWithKeyboard="4dp" ?

Thank you for this useful library

**Comment by qvinh0704** [comment]
> My problem is similar to this issue: https://stackoverflow.com/questions/17630336/space-between-keyboard-and-edittext-in-android
> 
> but because this otpview has its own background, I cannot modify the background as I pleased.
> 
> Maybe you should add one more attribute like app:distanceWithKeyboard="4dp" ?
> 
> Thank you for this useful library

You can add an EditText which is transparent into your layout, and make sure it's under an OtpView. After that, you need to setText() for OtpView on afterTextChanged() of EditText. Finally, you just add android:windowSoftInputMode="adjustPan" in AndroidManifest.xml for your activity. 
Hope this help.

**Comment by mukeshsolanki** [comment]
not an issue with the library
