### ISSUE TITLE
Support Rounded Rectangles

### ISSUE THREAD

**Issue by sdoward** [mukeshsolanki/android-otpview-pinview#80]
### Subject of the issue
Allow for a new type of RoundedRect

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by josephvijayandroiddev** [comment]
did you finished Round type....???

**Comment by aabhasr1** [comment]
Hi you can use https://github.com/aabhasr1/OtpView for rounded rectangles as I made a similar library taking inspiration from here

**Comment by josmilan** [comment]
Just create background resources with a rounded background. And set it as the itemBackground.

**Comment by mukeshsolanki** [comment]
thank you @josmilan
