### ISSUE TITLE
What is your latest version

### ISSUE THREAD

**Issue by ArsalanAbrar** [mukeshsolanki/android-otpview-pinview#82]
### Subject of the issue
Failed to resolve: com.github.mukeshsolanki:android-otpview-pinview:2.1.0

i am getting this error whats your latest version of this library

**Comment by pratikbutani** [comment]
Have you added this line in `build.gradle` of root level:

` maven { url "https://jitpack.io" }`

as below:

```
allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by bilabus** [comment]
still same problem, was add maven { url "https://jitpack.io" }

**Comment by dnsking** [comment]
You're supposed to add to the build script as well @bilabus and @pratikbutani 

```
buildscript {
    repositories {
        maven { url "https://jitpack.io" }
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
        
    }
}
```

**Comment by Miriam-Rachel** [comment]
this didn't work for me. the attribute: com.mukesh.OptView is still not recognized

**Comment by mehrajmuheeb** [comment]
@Miriam-Rachel  You are only supposed to add this in build.gradle(Project)
`allprojects {
    repositories {
        google()
        jcenter()
        maven { url "https://jitpack.io" }
    }
}`

**Comment by mehrajmuheeb** [comment]
> this didn't work for me. the attribute: com.mukesh.OptView is still not recognized

@Miriam-Rachel You are only supposed to add this in build.gradle(Project)
`allprojects { 
     repositories { 
                            google() 
                            jcenter() 
                            maven { url "https://jitpack.io" } 
                        }
      }`

**Comment by Miriam-Rachel** [comment]
Still not working :(
I added this and the 
implementation 'com.github.mukeshsolanki:android-otpview-pinview:2.1.2'
to build.gradle(app) as well

**Comment by Borlehandro** [comment]
Just add `maven { url 'https://jitpack.io' }` in your **settings.gradle** and it will work:
```
buildscript {
    repositories {
        google()
        mavenCentral()
        maven { url "https://jitpack.io" }
    }
}
```

**Comment by behroozAlborzi** [comment]
Just add ` maven { url 'https://jitpack.io' } ` in your settings.gradle  project  and it will work:
```
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
        maven { url "https://jitpack.io" }
    }

}
```

**Comment by Ajmalyousufz** [comment]
> Just add `maven { url 'https://jitpack.io' }` in your **settings.gradle** and it will work:
> 
> ```
> buildscript {
>     repositories {
>         google()
>         mavenCentral()
>         maven { url "https://jitpack.io" }
>     }
> }
> ```

Thank you Very much you are Great...
The maven url is add in settings.gradle 
any one get error in 2021 please look here
