### ISSUE TITLE
soft keypad not showing on click

### ISSUE THREAD

**Issue by FreedomChuks** [mukeshsolanki/android-otpview-pinview#83]
### Nothing happens onclick of the fields
No keypad coming up

**Comment by ArsalanAbrar** [comment]
Hii gzodx can you tell me the latest version??

**Comment by FreedomChuks** [comment]
I am using 2.0.1

**Comment by ArsalanAbrar** [comment]
Failed to resolve: com.github.mukeshsolanki:android-otpview-pinview:2.0.1 im getting this error

**Comment by FreedomChuks** [comment]
Add maven{url "https://jitpack.io"}

**Comment by chemickypes** [comment]
Resolved adding

```
android:focusable="true"
android:focusableInTouchMode="true"
```

to xml element

**Comment by pratikbutani** [comment]
Here is the solution: #39

**Comment by FreedomChuks** [comment]
Thanks
