### ISSUE TITLE
not open keyboar

### ISSUE THREAD

**Issue by alirezat66** [mukeshsolanki/android-otpview-pinview#85]
### Subject of the issue
I use this library and when I click on it , not open keyboard
### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo.

### Expected behaviour
It must open keyboard

### Actual behaviour
Not open keyboard

**Comment by andre-sonect** [comment]
Same issue here, keyboard does not open when click.

**Comment by ashishghadi27** [comment]
Did you add the style in styles.xml?

**Comment by anantshah93** [comment]
Same issue

**Comment by anantshah93** [comment]
Hi all, Please add this in your style.xml 

It will show the keyboard. - Solved Not bug

<style name="AppTheme" parent="Theme.AppCompat.Light.NoActionBar">
    
    <item name="otpViewStyle">@style/OtpWidget.OtpView</item>
  </style>

**Comment by Zulqurnain** [comment]
Adding `<item name="otpViewStyle">@style/OtpWidget.OtpView</item>` still same issue, keyboard doesn't open

**Comment by anantshah93** [comment]
@Zulqurnain  pls share your style.xml and your layout.xml where you have coded this layout

**Comment by inossan-dev** [comment]
I fix this issue by adding this attribute `style="@style/OtpWidget.OtpView"` in my `OtpView`

**Comment by inossan-dev** [comment]
Like this:

```
<com.mukesh.OtpView
     android:id="@+id/otp_view"
     android:layout_width="wrap_content"
     android:layout_height="wrap_content"
     android:inputType="numberPassword"
     android:textColor="@color/amount"
     android:layout_gravity="center"
     app:itemCount="4"
     style="@style/OtpWidget.OtpView"
     android:cursorVisible="false"
     app:lineColor="@color/amount"
     app:state_filled="false"
     app:viewType="none"/>
```
