### ISSUE TITLE
Can't change the itemBackground programmatically

### ISSUE THREAD

**Issue by whkumar** [mukeshsolanki/android-otpview-pinview#86]
### Subject of the issue
Can't change the itemBackground

### Steps to reproduce
otpView.setItemBackgroundResources(R.drawable.new_background).

### Expected behaviour
Item background should change

### Actual behaviour
Nothing happens

**Comment by mukeshsolanki** [comment]
@whkumar you can do this by using  ```otpView.setItemBackground(ResourcesCompat.getDrawable(getResources(),R.drawable.test_drawable,null));```
