### ISSUE TITLE
No round pin view input

### ISSUE THREAD

**Issue by princessdharmy** [mukeshsolanki/android-otpview-pinview#89]
@mukeshsolanki  There is no pin box's background, to accept a drawable or a selector drawable

For instance, the image below shows this by default then changes to a custom color on pin entered.
![20200218_115949](https://user-images.githubusercontent.com/27359181/74730385-4b231480-5246-11ea-9fd7-052021362166.jpg)

**Comment by mukeshsolanki** [comment]
@princessdharmy im not sure I fully understand what you are trying to achieve here can you provide me some more detail?

**Comment by GvinPin47** [comment]
@mukeshsolanki i also faced with the same issue like @princessdharmy, i want use different drawable for android:itemBackground via selector drawable smt like this

```
<selector xmlns:android="http://schemas.android.com/apk/res/android">
    <item android:state_selected="true" >
        <shape android:shape="rectangle">
            <corners android:radius="10dp" />
            <stroke android:width="1dp" android:color="@color/primaryColor" />
            </shape>
    </item>
    <item android:state_focused="true" >shape..</item>
    <item > shape...</item>
</selector>
```

**Comment by princessdharmy** [comment]
@mukeshsolanki sorry for the late response. I can't say precisely what the issue was since it has been a long time I tried my hands on the library.
I presume @GvinPin47 must have a similar experience.

**Comment by mukeshsolanki** [comment]
stale
