### ISSUE TITLE
Copy paste of OTP is not working

### ISSUE THREAD

**Issue by souravpalitrana** [mukeshsolanki/android-otpview-pinview#93]
### Copy paste of OTP is not working
Copy the code and try to paste on OTP view. Copy/Paste is not working.

**Comment by vincent-paing** [comment]
Have you found a workaround for this?

**Comment by souravpalitrana** [comment]
Just made my own otp view instead of using this.

**Comment by mukeshsolanki** [comment]
it should be available in the new build

**Comment by anoopmca51** [comment]
@mukeshsolanki by when we get new build?
