### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by hameedolamide** [mukeshsolanki/android-otpview-pinview#97]
### Subject of the issue
The project does not build after adding the dedendencies in duild.gradle file, giving this error "ERROR: Unable to resolve dependency for ':app@debug/compileClasspath': Could not resolve com.github.mukeshsolanki:android-otpview-pinview:<latest-version>."

### Steps to reproduce
Tell us how to reproduce this issue. Please provide a working demo.

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by ahmed56734** [comment]
same with me
Could not find com.github.mukeshsolanki:android-otpview-pinview:2.1.0.

**Comment by hudaolayan** [comment]
this solved here issue #82
