### ISSUE TITLE
View not clickable focusable. Cannot input any digit and open keyboard

### ISSUE THREAD

**Issue by davran312** [mukeshsolanki/android-otpview-pinview#98]
### Subject of the issue
After setup view. Cannot input anything

### Steps to reproduce
     <com.mukesh.OtpView
            android:id="@+id/et_otp_view"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            app:viewType="line"
            app:lineColor="@color/lightGray"
            android:textColor="@color/textNumberColorPrimary"
            android:inputType="number"
            android:layout_marginTop="@dimen/vertical_huge_margin"
            app:layout_constraintStart_toStartOf="parent"
            app:layout_constraintEnd_toEndOf="parent"
            app:layout_constraintTop_toBottomOf="@id/tv_enter_pin_code"/>

### Expected behaviour
Tell us what should happen

### Actual behaviour
Tell us what happens instead

**Comment by JibuVarghese** [comment]
@davran312 you might forget to add <item name="otpViewStyle">@style/OtpWidget.OtpView</item> in your style.

**Comment by akshat8-7** [comment]
Did you solve this issue ?

**Comment by imranshad** [comment]
> @davran312 you might forget to add @style/OtpWidget.OtpView in your style.

also make sure to add style 
```
<com.mukesh.OtpView
.............
style="@style/OtpWidget.OtpView"
.................. />
```
